# -*- coding: utf-8 -*-
"""HW5_Refactored Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Iv3QcYxtkzll5prbkdRMuIICGF7bZOX
"""

"""
Homework #5 - Refactoring and Documenting Code
"""

import pandas as pd
import matplotlib.pyplot as plt

def compute_stats(data):
    # take average and std of "value" column
    if "value" not in data.columns or data.empty:
        print("Problem: data is empty or missing 'value' column.")
        return None, None
    avg = data["value"].mean()
    std = data["value"].std()
    return avg, std

def show_samples(data, n=5):
    # show n random rows
    if data.empty:
        print("No data to sample")
    else:
        print(data.sample(n=n))

# --- main script ---
try:
    data = pd.read_csv("data.csv")
except:
    print("Could not read file")
    data = pd.DataFrame()

if not data.empty and "value" in data.columns:
    avg, std = compute_stats(data)
    if avg is not None:
        print("Average is:", avg)
        print("Std dev is:", std)

    print("Sample rows:")
    show_samples(data, 5)

    plt.plot(data["value"])
    plt.title("Values")
    plt.show()
else:
    print("No valid data available.")


# test 1: normal case
print("test 1: normal case")
df = pd.DataFrame({"value": [1, 2, 3]})
avg, std = compute_stats(df)
assert round(avg, 1) == 2.0
print("Test passed for correct data!")

# test 2: empty dataframe
print("test 2: empty dataframe")
empty_df = pd.DataFrame({"value": []})
avg, std = compute_stats(empty_df)
print("Empty test out")